name: type_caster
description: A powerful type casting and conversion library for Dart that provides safe and flexible type conversion utilities.
version: 0.1.1
repository: https://github.com/venhdev/type_caster_dart
homepage: https://github.com/venhdev/type_caster_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
