name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Matches version tags more precisely

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for pub.dev token

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Analyze code
        run: dart analyze --fatal-infos

      - name: Publish package
        uses: k-paxian/dart-package-publisher@v1.5.1
        with:
          credentialJson: ${{ secrets.PUB_CREDENTIALS_JSON }}
          flutter: true
          skipTests: true # Since we already ran tests
          force: true
